recon/urls.py
from django.conf.urls import patterns, url, include
from django.views.generic import TemplateView, ListView, RedirectView
from recon import views

urlpatterns = patterns('',
                       url(r'^$', views.site_home, name='home'),
                       url(r'^topic/(?P<topic_id>\d+)/$',
                           views.networkgraph,
                           name='dashboard'),
                       url(r'^topic/(?P<topic_id>\d+)/data.json$',
                           views.get_network_graph_data,
                           name='get_network_graph_data'),
                       url(r'^topic/(?P<topic_id>\d+)/twitter-network-graph/$',
                           views.tw_networkgraph,
                           name='twitter_network_graph'),
                       url(r'^topic/(?P<topic_id>\d+)/twitter-network-graph/data.json$',
                           views.tw_get_network_graph_data,
                           name='twitter_get_network_graph_data'),

                       url(r'^topic/new/$',
                           views.new_topic,
                           name='new_topic'),
                       url(r'^topic/(?P<topic_id>\d+)/twitter-barchart/$',
                           views.barchart_twitter,
                           name='barchart_twitter'),
                       url(r'^topic/(?P<topic_id>\d+)/barchart/$',
                           views.barchart,
                           name='barchart'),
                       url(r'^topic/(?P<topic_id>\d+)/citation/$',
                           views.citation,
                           name='citation'),
                       url(r'^topic/(?P<topic_id>\d+)/twitter-citation/$',
                           views.twitter_citation,
                           name='twitter_citation'),

                       url(r'^topic/(?P<topic_id>\d+)/(?P<list_name>.+)/manage/$',
                           views.list,
                           name='list'),
                       url(r'^topic/(?P<topic_id>\d+)/(?P<list_name>.+)/manage/new/$',
                           views.create,
                           name='new'),
                       url(r'^topic/(?P<topic_id>\d+)/(?P<list_name>.+)/manage/edit/(?P<id>\d+)/$',
                           views.update,
                           name='edit'),
                       url(r'^topic/(?P<topic_id>\d+)/(?P<list_name>.+)/manage/delete/(?P<id>\d+)/$',
                           views.delete,
                           name='delete'),
                       url(r'^topic/(?P<topic_id>\d+)/crawler/get_crawl_log$',
                           views.get_crawl_log,
                           name='get_crawl_log'),
                       url(r'^topic/(?P<topic_id>\d+)/twitter-crawler/get_crawl_log_twitter$',
                           views.get_crawl_log_twitter,
                           name='get_crawl_log_twitter'),
                       url(r'^topic/(?P<topic_id>\d+)/crawler/$',
                           views.crawler,
                           name='crawler'),
                       url(r'^topic/(?P<topic_id>\d+)/twitter-crawler/$',
                           views.twitter_crawler,
                           name='twitter_crawler'),
                       url(r'^js/', include('djangojs.urls')),
                       url(r'^topic/(?P<topic_id>\d+)/warc/(?P<warc_url>.+)',
                           views.recon_frame,
                           name='crawler'),
                       )

recon_site/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.shortcuts import render
from django.views.generic import TemplateView
admin.site.site_header = 'RECON - CSCC01 Team 3'

urlpatterns = patterns('',
                       url(r'', include('recon.urls')),
                       url(r'^admin/', include(admin.site.urls)),
                       url(r"^account/", include("account.urls")),
                       )

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recon/models.py
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.core.validators import URLValidator
from django.db import models
import urlparse
# Create your models here.


class ReconTopic(models.Model):

    def list_name(self):
        return

    def __unicode__(self):
        return(self.topic)

    def get_crawl_status(self):
        for choice in self.STATUS_CHOICES:
            if self.crawl_status == choice[0]:
                return choice[1]

    def get_twitter_status(self):
        for choice in self.STATUS_CHOICES:
            if self.twitter_status == choice[0]:
                return choice[1]
    READY = 0
    RUNNING = 1
    STOP = 2
    STATUS_CHOICES = (
        (READY, 'Ready'),
        (RUNNING, 'Running'),
        (STOP, 'Stop'),
    )
    topic = models.CharField(max_length=200, unique=True)
    user = models.ForeignKey(User)
    crawl_status = models.IntegerField(choices=STATUS_CHOICES, default=READY)
    twitter_status = models.IntegerField(choices=STATUS_CHOICES, default=READY)


class SearchList(models.Model):
    CHOICES = (
        (0, 'No'),
        (1, 'Yes'),
    )

    def clean(self):
        # Don't allow draft entries to have a pub_date.
        if self.is_url == 1:
            validate = URLValidator()
            try:
                url_fields = list(urlparse.urlsplit(self.term))
                if not url_fields[0]:
                    # If no URL scheme given, assume http://
                    url_fields[0] = 'http'
                if not url_fields[1]:
                    # Assume that if no domain is provided, that the path segment
                    # contains the domain.
                    url_fields[1] = url_fields[2]
                    url_fields[2] = ''
                    # Rebuild the url_fields list, since the domain segment may now
                    # contain the path too.
                url = urlparse.urlunsplit(url_fields)
                validate(url)
                self.term = url
            except ValidationError as e:
                raise ValidationError(e)

    def name(self):
        return self.term

    def __unicode__(self):
        return('[' + str(self.topic_fk) + ']' + self.term)

    term = models.CharField(max_length=200)
    is_url = models.IntegerField(choices=CHOICES, default=1)
    topic_fk = models.ForeignKey(ReconTopic)


class WatchList(models.Model):

    def name(self):
        return self.url

    def __unicode__(self):
        return('[' + str(self.topic_fk) + ']' + self.url)

    url = models.URLField(max_length=200)
    topic_fk = models.ForeignKey(ReconTopic)


class Citation(models.Model):

    def __unicode__(self):
        return('[' + str(self.topic_fk) + ']' + self.url_title + ' --> ' + self.links_to)

    def has_hyperlink(self):
        return (self.links_to.startswith("http"))

    topic_fk = models.ForeignKey(ReconTopic)
    watch_fk = models.ForeignKey(WatchList)
    search_fk = models.ForeignKey(SearchList)
    url = models.URLField(max_length=200)
    url_title = models.CharField(max_length=200)
    links_to = models.CharField(max_length=200)
    publish_timestamp = models.DateTimeField(null=True)
    crawled_timestamp = models.DateTimeField(null=True)


class TwitterHandle(models.Model):

    def __unicode__(self):
        return(self.handle)

    def name(self):
        return self.handle
    handle = models.CharField(max_length=18)
    topic_fk = models.ForeignKey(ReconTopic)
    tweet_count = models.IntegerField(default=20)


class TwitterCitation(models.Model):

    def __unicode__(self):
        return('[' + str(self.topic_fk) + ']' + str(self.handle_fk) + "->" + self.links_to)

    topic_fk = models.ForeignKey(ReconTopic)
    handle_fk = models.ForeignKey(TwitterHandle)
    search_fk = models.ForeignKey(SearchList)
    links_to = models.CharField(max_length=200)
    tweet = models.CharField(max_length=200)
    datetime = models.DateTimeField()

recon/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.forms import TextInput
from django.utils.translation import ugettext_lazy as _

from recon.models import ReconTopic, SearchList, WatchList, TwitterHandle


class ReconTopicForm(forms.ModelForm):

    class Meta:
        model = ReconTopic
        fields = ['topic', 'user']
        widgets = {
            'topic': TextInput(attrs={'size': '40', 'class': 'myfieldclass'}),
        }


class SearchListForm(forms.ModelForm):

    class Meta:
        model = SearchList
        fields = '__all__'
        widgets = {
            'term': TextInput(attrs={'size': '40', 'class': 'myfieldclass'}),
        }


class WatchListForm(forms.ModelForm):

    class Meta:
        model = WatchList
        fields = '__all__'
        widgets = {
            'url': TextInput(attrs={'size': '40', 'class': 'myfieldclass'}),
        }


class TwitterHandleForm(forms.ModelForm):

    class Meta:
        model = TwitterHandle
        fields = '__all__'
        widgets = {
            'handle': TextInput(attrs={'size': '40', 'class': 'myfieldclass'}),
        }

recon/templates/recon/bar_chart.html
{% extends "recon/recon_base.html" %}
{% load js staticfiles %}

{% block page_style %}
	{% css "recon/css/barchart.css" %}
{% endblock %}

{% block recon_content%}

<div id="barchart"></div>

{% endblock %}

{% block page_script %}

{% js "recon/js/d3.js" %}
{% js "recon/js/c3.js" %}
{% js "recon/js/barchart.js" %}

<script type="text/javascript">

	var json = {{json_data|safe}};

	$(document).ready(function() {

		var domChart = $("#barchart");
		if (json.length == 0) {
			domChart.innerHTML("<h1>No Citation is Found.</h1>");
		} else {

			var xs = [];
			var ys = [];

			$.each(json, function(i, d) {
				xs.push(d.name);
				ys.push(d.count);
			});

			var chart = domChart.barChart({tooltip_title: "Article Name: ", color: "#5F9F9F",
										   tooltip_data_name: "Number of Reference",
										   ylabel: "Number of Reference"},
										  {x: xs, y: ys});
		}
	});
</script>
{% endblock %}


recon/templates/recon/citation.html
{% extends "recon/recon_base.html" %}
{% load js staticfiles eztables %}

{% block page_style %}
	{% datatables_bootstrap_css %}
{% endblock %}

{% block recon_content%}
	<h3>Web Citations</h3>
    <table style="display:none" id="browser-table" class="span12 table table-bordered table-condensed table-striped table-hover">
        <thead>
            <tr>
                <th>Title</th>
                <th>Links to</th>
                <th>Date Added</th>
            </tr>
        </thead>
        <tbody>
	{% for url_citation_list in citation_list %}
    	<tr>
        <td valign="top"><a href="/topic/{{topic_id}}/warc/{{ url_citation_list.0.url }}/">{{ url_citation_list.0.url_title }}</a></td> 
        	<td>
        	<ul>
        	{% for citation in url_citation_list %}
        		<li>
					{% if citation.has_hyperlink %}
        			<a href="/topic/{{topic_id}}/warc/{{ citation.links_to }}/">{{ citation.links_to }}</a>
		        {% else %}
        			{{ citation.links_to }}
        		{% endif %}
        		</li>
        	{% endfor %}
        	</ul>
        	</td>
        	<td>
        		{{url_citation_list.0.crawled_timestamp}}
        	</td>
        </tr>
    {% endfor %}
        </tbody>
    </table>

{% endblock %}

{% block page_script %}
 {% django_js %}
 {% datatables_js %}
 {% datatables_bootstrap_js %}
 {% js "recon/js/eztables.demo.js" %}
 {% js "recon/js/eztables.client.js" %}
 <script>
 $(document).ready(function(){          
     $(".pagination > ul").addClass('pagination');
	 $('#browser-table').show();
});
</script>
{% endblock %}

recon/templates/recon/confirm_delete.html
{% extends "recon/recon_base.html" %}
{% load staticfiles %}

{% block recon_content %}
<form method="post">{% csrf_token %}
    Are you sure you want to delete "{{ object }}" ?
    <input type="submit" value="Submit" />
</form>
{% endblock %}

recon/templates/recon/crawler.html
{% extends "recon/recon_base.html" %}
{% load staticfiles %}

{% block recon_content %}
<h3>{{title}}</h3>
<h4>Status : {{status}}</h4>

<form method="post">
    {% csrf_token %}
    <input type="submit" value="Start" name="_start" {% if state == 1%} disabled {% endif %}>
    <input type="submit" value="Stop" name="_stop" {% if state == 0 or state == 2%} disabled {% endif %}>
</form>
<textarea id="log" rows="17" cols="100">
</textarea>

{% endblock %}

{% block page_script %}
<script>

function doUpdate() {
  $.ajax({type: "GET", url : "get_crawl_log",
          success: function (data) {
             if (data.length > 4)
             {
                $("textarea#log").val(data);
             }
             setTimeout("doUpdate()", 2000);
           }});
}
setTimeout("doUpdate()", 1000);
</script>
{% endblock %}

recon/templates/recon/form.html
{% extends "recon/recon_base.html" %}
{% load staticfiles %}

{% block recon_content %}
	<form action="" method="post">
	    {% csrf_token %}
	    {{ form.as_p }}
	    <input type="submit" value="Submit" />
	</form>
{% endblock %}

recon/templates/recon/home.html
{% extends "banner_base.html" %}
{% load staticfiles %}
{% load webdesign %}

{% block head_title %}Welcome{% endblock %}

{% block body_class %}home{% endblock %}

{% block extra_style %}
	<link href="{% static 'recon/style.css' %}" rel="stylesheet">
{% endblock %}

{% block banner %}
    <h1>Welcome to Recon</h2>
    {% if user.is_authenticated %}
    	<h2>My topics:</h3>
    		<ul>
	        {% for topic in topic_list %}
	        	<li>
	        		<a href="/topic/{{topic.id}}/"> <h3>{{ topic.topic }}</h3></a>
	        	</li>
	        {% endfor %}
	        <li><a href="{% url 'new_topic' %}">Add Topic</a></li>
	    	</ul>    
	
	    <div id="content">
	        
	    </div>

    {% else %}
        
        {% url "account_login" as login_url %}
        {% url "account_signup" as signup_url %}
        <p>You can <a href="{{ login_url }}" class="btn btn-default">Log In</a> or <a href="{{ signup_url }}" class="btn btn-primary">Sign Up</a> to have access to the site.</p>
    {% endif %}
{% endblock %}

recon/templates/recon/list.html
{% extends "recon/recon_base.html" %}
{% load staticfiles %}
{% load js staticfiles eztables %}

{% block page_style %}
	{% datatables_bootstrap_css %}
{% endblock %}

{% block recon_content %}
<h3>{{title}}</h3>
<h5>{{explain}}</h5>
<table id="browser-table" class="span12 table table-bordered table-condensed table-striped table-hover">
{% block list_table %}
	<thead>
    <th width="90%">Title</th>
    <th width="5%"></th>
    <th width="5%"></th>
    </thead>
    <tbody>
    {% for item in object_list %}
    <tr>
    <td>{{item.name}}</td>
    <td><a  class="btn btn-default" role="button" href="{% url "edit" topic_id=topic_id list_name=list_name id=item.id %}">edit</a></td>
    <td><a  class="btn btn-default" role="button" href="{% url "delete" topic_id=topic_id list_name=list_name id=item.id %}">delete</a></td>
    </tr>
    {% endfor %}
    </tbody>
{% endblock %}
</table>

<a  class="btn btn-primary" role="button" href="{% url "new" topic_id=topic_id list_name=list_name%}">Add New</a>
{% endblock %}

{% block page_script %}
{% django_js %}
 {% datatables_js %}
 {% datatables_bootstrap_js %}
{% endblock %}

recon/templates/recon/network_graph.html
{% extends "recon/recon_base.html" %}

{% block recon_content%}
<style>

.node {
  stroke: #fff;
  stroke-width: 1.5px;
}

.link {
  stroke: #999;
  stroke-opacity: .6;
}

.svg {
	display: block;
    margin-left: 250px;
}

</style>
<script src="http://d3js.org/d3.v3.min.js"></script>
<script>

var width = 900,
    height = 600;

var color = d3.scale.category20();

var force = d3.layout.force()
    .charge(-400)
    .linkDistance(300)
    .size([width, height]);
    
var drag = force.drag()
    .on("dragstart", dragstart);
    
var svg = d3.select("body").append("svg")
    .attr("width", width)
    .attr("height", height)
    .style("margin-left", "250px");
d3.json("{% url 'get_network_graph_data' topic_id=topic_id %}", function(error, graph) {
  force
      .nodes(graph.nodes)
      .links(graph.links)
      .start();

  var link = svg.selectAll(".link")
      .data(graph.links)
    .enter().append("line")
      .attr("class", "link")
      .style("stroke-width", function(d) { return d.value; });

  var node = svg.selectAll(".node")
      .data(graph.nodes)
    .enter().append("circle")
      .attr("class", "node")
      .attr("r", function(d) { return d.size; })
      .style("fill", function(d) { return color(d.group); })
      .on("dblclick", dblclick)
      .call(drag);
  
  
  node.append("title")
      .text(function(d) { return d.name; });

  force.on("tick", function() {
    link.attr("x1", function(d) { return d.source.x; })
        .attr("y1", function(d) { return d.source.y; })
        .attr("x2", function(d) { return d.target.x; })
        .attr("y2", function(d) { return d.target.y; });

    node.attr("cx", function(d) { return d.x = Math.max(0, Math.min(width, d.x)); })
        .attr("cy", function(d) { return d.y = Math.max(0, Math.min(height, d.y)); });
        
    
	});
});


function dblclick(d) {
  d3.select(this).classed("fixed", d.fixed = false);
}

function dragstart(d) {
  d3.select(this).classed("fixed", d.fixed = true);
}

</script>

{% endblock %}

recon/templates/recon/recon_base.html
{% extends "site_base.html" %}
{% load staticfiles %}
{% load i18n %}

{% block head_title %}{{topic_title}}{% endblock %}
{% block extra_style %}
    <link href="{% static 'recon/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'recon/css/simple-sidebar.css' %}" rel="stylesheet">
	<link href="{% static 'recon/style.css' %}" rel="stylesheet">	
	{% block page_style %}
	{% endblock %}
{% endblock %}

{% block body_base %}
    
	<div id="wrapper">
        <!-- Sidebar -->
        <div id="sidebar-wrapper">
            <ul class="sidebar-nav">
                <li>
                	{% url 'crawler' topic_id=topic_id as crawler %}
                    <a href="{{crawler}}" {% if request.path == crawler %} class="active"{% endif %}>
                        Manage Web Crawl
                    </a>
                </li>
                <li>
                	{% url 'twitter_crawler' topic_id=topic_id as twitter_crawler %}
                    <a href="{{twitter_crawler}}" {% if request.path == twitter_crawler %} class="active"{% endif %}>
                        Manage Twitter Crawl
                    </a>
                </li>
                <h4> Topic</h4>
                <li>
                	{% url 'dashboard' topic_id=topic_id as dashboard%}
                    <a href="{{dashboard}}" {% if request.path == dashboard %} class="active"{% endif %}>Network Graph</a>
                </li>
		<li>
			        <li>
                	{% url 'twitter_network_graph' topic_id=topic_id as twitter_network_graph%}
                    <a href="{{twitter_network_graph}}" {% if request.path == twitter_network_graph %} class="active"{% endif %}>Twitter Network Graph</a>
                </li>
		<li>
                	{% url 'barchart' topic_id=topic_id as barchart%}
                    <a href="{{barchart}}" {% if request.path == barchart %} class="active"{% endif %}>Barchart</a>
                </li>
                <li>
                	{% url 'barchart_twitter' topic_id=topic_id as barchart_twitter%}
                    <a href="{{barchart_twitter}}" {% if request.path == barchart_twitter %} class="active"{% endif %}>Twitter Barchart</a>
                </li>
                <li>
                {% url 'list' topic_id=topic_id list_name='domain' as manage_domain %}
                    <a href="{{manage_domain}}" {% if request.path == manage_domain %} class="active"{% endif %}>
                	Manage Search Domain</a>
                </li>
                <li>
                	{% url 'list' topic_id=topic_id list_name='keyword' as manage_keyword %}
                    <a href="{{manage_keyword}}" {% if request.path == manage_keyword %} class="active"{% endif %}>
                    Manage Search Keywords</a>
                </li>
                <h4> Website</h4>
                <li>
                    {% url 'list' topic_id=topic_id list_name='watch' as manage_watch %}
                    <a href="{{manage_watch}}" {% if request.path == manage_watch %} class="active"{% endif %}>
                    Manage Site Watch List</a>
                </li>
                <li>
                    {% url 'citation' topic_id=topic_id as citation %}
                    <a href="{{citation}}" {% if request.path == citation %} class="active"{% endif %}>
					View Web Citations</a>
                </li>
                <h4> Twitter</h4>
                <li>
                    {% url 'list' topic_id=topic_id list_name='handle' as manage_handle %}
                    <a href="{{manage_handle}}" {% if request.path == manage_handle %} class="active"{% endif %}>
                    Manage Twitter Watch List</a>
                </li>
                <li>
                	{% url 'twitter_citation' topic_id=topic_id as twitter_citation %}
                    <a href="{{twitter_citation}}" {% if request.path == twitter_citation %} class="active"{% endif %}>
					View Twitter Citations</a>
                </li>
                <li>&nbsp;</li>
                
                
                
            </ul>
        </div>
        <!-- /#sidebar-wrapper -->		
        <!-- Page Content -->
        
        <div class="navbar navbar-inverse" style="margin-bottom: 0px;">    
		    <a href="#menu-toggle" id="menu-toggle" class="nav-expander navbar-left">
		    MENU &nbsp;<i class="fa fa-bars fa-lg white"></i>
		  </a>
		    <a class="navbar-brand" href="#">{% block recon_title %}    Topic : {{topic_title}}{% endblock %}</a>
		    
		</div>


        {% block page_content%}
        <div id="page-content-wrapper">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-12">
                    	
                    	{% block recon_content%}
                        
                        <h3>Work in progress... Not implemeneted yet</h3>
                        
                        {% endblock %}
                    </div>
                </div>
            </div>
        </div>
        {% endblock %}
	</div>
                    
    </div>
    

{% endblock %}

{% block footer_base %}
{% endblock %}

{% block extra_script %}
    
    <!-- Menu Toggle Script -->
    {% if topic_id %}
		<script>
		$("#menu-toggle").click(function(e) {
		    $("#wrapper").toggleClass("toggled");
		});
		</script>    	
	{% else %}
		<script>
			$("#wrapper").addClass("toggled");
		</script>   
    {% endif %}
    {% block page_script %}
    {% endblock %}
{% endblock %}

recon/templates/recon/recon_frame.html
{% extends "recon/recon_base.html" %}
{% block page_style %}

{% endblock %}

{% block recon_title %}
This is an <b>Archived</b> page<span id="archive_date"></span>.
{% endblock %}
{% block page_content%}
<iframe id="warc_frame" src="/warc/replay/{{ warc_url }}" style="height:500px">
    <p>Unable to create a warc view</p>
</iframe>

<p id="demo"></p>

{% endblock %}

{% block page_script %}    

<script>
window.myfunction = function (timestamp) {
  document.getElementById("archive_date").innerHTML =  " from <b>" + ts_to_date(timestamp, false) + "</b>";
}

function ts_to_date(ts, is_gmt)
{
    if (ts.length < 14) {
        return ts;
    }
    
    var datestr = (ts.substring(0, 4) + "-" + 
                  ts.substring(4, 6) + "-" +
                  ts.substring(6, 8) + "T" +
                  ts.substring(8, 10) + ":" +
                  ts.substring(10, 12) + ":" +
                  ts.substring(12, 14) + "-00:00");
    
    var date = new Date(datestr);
    if (is_gmt) {
        return date.toGMTString();
    } else {
        return date.toLocaleString();
    }
}
</script>

{% endblock %}

recon/templates/recon/twitter-crawler.html
{% extends "recon/recon_base.html" %}
{% load staticfiles %}

{% block recon_content %}
<h3>{{title}}</h3>
<h4>Status : {{status}}</h4>

<form method="post">
    {% csrf_token %}
    <input type="submit" value="Start" name="_start" {% if state == 1%} disabled {% endif %}>
    <input type="submit" value="Stop" name="_stop" {% if state == 0 or state == 2 %} disabled {% endif %}>
</form>
<textarea id="log" rows="17" cols="100">
</textarea>

{% endblock %}

{% block page_script %}
<script>
function doUpdate() {
  $.ajax({type: "GET", url : "get_crawl_log_twitter" ,
          success: function (data) {
             if (data.length > 4)
             {
                $("textarea#log").val(data);
             }
             setTimeout("doUpdate()", 2000);
           }});
}
setTimeout("doUpdate()", 1000);
</script>
{% endblock %}

recon/templates/recon/twitter_citation.html
{% extends "recon/recon_base.html" %}
{% load js staticfiles eztables %}

{% block page_style %}
	{% datatables_bootstrap_css %}
{% endblock %}

{% block recon_content%}

<div class="row">
    <table id="browser-table" class="span12 table table-bordered table-condensed table-striped table-hover">
        <thead>
            <tr>
    <th width="15%">Handle</th>
    <th width="40%">Tweet</th>
    <th width="30%">Links to</th>
    <th width="15%">Time Tweeted</th>
                </tr>
        </thead>
        <tbody>
    
    {% for each in citation_list %}
    	<tr>
	    <td>{{ each.handle_fk}}</td>
	    <td>{{ each.tweet }}</td>
	    <td>{{ each.links_to }}</td>
	    <td>{{ each.datetime }}</td>
	</tr>
    {% endfor %}
    </tbody>
    </table>

{% endblock %}


{% block page_script %}
 {% django_js %}
 {% datatables_js %}
 {% datatables_bootstrap_js %}
 {% js "recon/js/eztables.demo.js" %}
 {% js "recon/js/eztables.client.js" %}
 <script>
 $(document).ready(function(){          
     $(".pagination > ul").addClass('pagination');
});
</script>
{% endblock %}

recon/templates/recon/twitter_handle_list.html
{% extends "recon/list.html" %}
	
	{% block list_table %}
	<thead>
    <th width="80%">Handle</th>
    <th width="10%">Count</th>
    <th width="5%"></th>
    <th width="5%"></th>
    </thead>
    <tbody>
    {% for item in object_list %}
    <tr>
    <td>{{item.name}}</td>
    <td>{{item.tweet_count}}</td>
    <td><a  class="btn btn-default" role="button" href="{% url "edit" topic_id=topic_id list_name=list_name id=item.id %}">edit</a></td>
    <td><a  class="btn btn-default" role="button" href="{% url "delete" topic_id=topic_id list_name=list_name id=item.id %}">delete</a></td>
    </tr>
    {% endfor %}
    </tbody>
    {% endblock %}

recon/templates/recon/twitter_network_graph.html
{% extends "recon/recon_base.html" %}

{% block recon_content%}
<style>

.node {
  stroke: #fff;
  stroke-width: 1.5px;
}

.link {
  stroke: #999;
  stroke-opacity: .6;
}

.svg {
	display: block;
    margin-left: 250px;
}

</style>
<script src="http://d3js.org/d3.v3.min.js"></script>
<script>

var width = 900,
    height = 600;

var color = d3.scale.category20();

var force = d3.layout.force()
    .charge(-400)
    .linkDistance(300)
    .size([width, height]);
    
var drag = force.drag()
    .on("dragstart", dragstart);
    
var svg = d3.select("body").append("svg")
    .attr("width", width)
    .attr("height", height)
    .style("margin-left", "250px");
d3.json("{% url 'twitter_get_network_graph_data' topic_id=topic_id %}", function(error, graph) {
  force
      .nodes(graph.nodes)
      .links(graph.links)
      .start();

  var link = svg.selectAll(".link")
      .data(graph.links)
    .enter().append("line")
      .attr("class", "link")
      .style("stroke-width", function(d) { return d.value; });

  var node = svg.selectAll(".node")
      .data(graph.nodes)
    .enter().append("circle")
      .attr("class", "node")
      .attr("r", function(d) { return d.size; })
      .style("fill", function(d) { return color(d.group); })
      .on("dblclick", dblclick)
      .call(drag);
  
  
  node.append("title")
      .text(function(d) { return d.name; });

  force.on("tick", function() {
    link.attr("x1", function(d) { return d.source.x; })
        .attr("y1", function(d) { return d.source.y; })
        .attr("x2", function(d) { return d.target.x; })
        .attr("y2", function(d) { return d.target.y; });

    node.attr("cx", function(d) { return d.x = Math.max(0, Math.min(width, d.x)); })
        .attr("cy", function(d) { return d.y = Math.max(0, Math.min(height, d.y)); });
        
    
	});
});


function dblclick(d) {
  d3.select(this).classed("fixed", d.fixed = false);
}

function dragstart(d) {
  d3.select(this).classed("fixed", d.fixed = true);
}

</script>

{% endblock %}